### ISSUE TITLE
JOSS: Docker installation

### ISSUE THREAD

**Issue by mhubii** [ARC-OPT/wbc#108]
Under https://arc-opt.github.io/Documentation/installation/installation_no_rock.html, would it be possible to explain how to install / run docker, along the lines of `docker build . -t wbc` or what not

Refers to https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
done

**Comment by mhubii** [comment]
using `git clone git@github.com:ARC-OPT/wbc.git` does require access rights, consider https
