### ISSUE TITLE
JOSS: typos

### ISSUE THREAD

**Issue by mhubii** [ARC-OPT/wbc#110]
- `QPOases` -> `qpOASES`, e.g. here: https://arc-opt.github.io/Documentation/tutorials/vel_using_different_solver.html
- Also minor: "allows inequality constraints, e.g.., joint velocity limits": e.g.. -> e.g. (https://arc-opt.github.io/Documentation/tutorials/vel_using_different_solver.html)
- ROS2 -> ROS 2 (https://shouldiputaspacebetweenrosand2.com/) :D

Refers to https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
Fixed minor
