### ISSUE TITLE
JOSS: Mute solver

### ISSUE THREAD

**Issue by mhubii** [ARC-OPT/wbc#111]
I've been running through introduction https://arc-opt.github.io/Documentation/tutorials/vel_introductory_example.html inside Docker.

Reading through Doxygen (https://arc-opt.github.io/wbc/classwbc_1_1QPSolver.html), I can't find a means of "muting" the output. Muting output seems? desirable 

Refers to https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
The output is not in the solver but in the tutorial itself to show the user what happens. The solver itself should not write output on the cmd line.
