### ISSUE TITLE
[JOSS Review] Support Ubuntu 24.04 / ROS 2 Jazzy

### ISSUE THREAD

**Issue by sea-bass** [ARC-OPT/wbc#115]
Right now, the tool is only documented to work with Ubuntu 20.04 and 22.04, but 24.04 has been out for a while.

My personal laptop runs 24.04, so I could only test in the Docker container which limited what I could try out.

https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
I added support for Ubuntu24.04 and ROS 2 jazzy
