### ISSUE TITLE
[JOSS Review] Paper Feedback

### ISSUE THREAD

**Issue by sea-bass** [ARC-OPT/wbc#117]
This issue tracks my comments on the JOSS submission publication for ARC-OPT WBC.

Please refer to https://github.com/openjournals/joss-reviews/issues/6696 for my overall comments and links to other issues.

---

- [x] Overall, the paper is very short. While JOSS publications are not intended to be as rigorous as academic conference/journals, I think more details throughout the whole publications are necessary.
- [x] At least one more figure is necessary that shows visualization of a robot model from tje actual software -- something like the KUKA iiwa videos embedded in the tutorial documentation, but of course it would be more impactful if you picked a more complex kinematic tree such as a full humanoid.
- [x] The "State of the field" criterion for the paper is not currently being met, and needs to be added. Specifically, there needs to be comparisons with other open-source tools for whole-body control. Please consider doing some review including tools like these, among others that I am for sure missing.
  - [x] As users of Pinocchio, you can refer to related tools like [Humanoid Path Planner (HPP)](https://humanoid-path-planner.github.io/hpp-doc/), [OCS2](https://leggedrobotics.github.io/ocs2/) and [Crocoddyl](https://github.com/loco-3d/crocoddyl).
  - [x] Other popular stack of tasks approaches include Stephane Caron's [Pink](https://github.com/stephane-caron/pink), also based on Pinocchio, and the related [Mink](https://github.com/kevinzakka/mink) from Kevin Zakka, which is based on MuJoCo. 
  - [x] I've also recently learned about the [humanoid control stack from IIT](https://github.com/ami-iit). These are only a few suggestions, and I'm sure many more can be found.
- [x] It is typical, and in my opinion required, for a JOSS paper to speak somewhat about the software.
  - [x] The design is briefly introduced, but could use more detail (as with the whole paper)
  - [x] The Example introduced how to set up a QP for whole-body control generically, but I strongly suggest then showing an actual code snippet from WBC showing how easy it is to translate the mathematical formulation into code. It's a major point of submissions to this journal.
  - [x] Finally, you are doing your great work a disservice by not mentioning that these tools have Python bindings and ROS 2 support, and integrate with `ros2_control`. Please include this information, as it's good!
- [x] There is one sentence that (very) briefly explains WBC's support for floating base dynamics, friction cone constraints, cost weighting, and task hierarchies. I think this part in particular could use a bit more fleshing out, as well as pointing to the fact that most of these are actually available as tutorials. The only one I didn't find was the friction cone constraint, but everything else was for sure there.

**Comment by dmronga** [comment]
Thanks a lot for the detailed comments, I will consider them as much as possible. Just some rebuttals from my side:
* Paper length: Agreed I will add more detailed explanations, but according to [here](https://joss.readthedocs.io/en/latest/paper.html) there is a page limit of 1000 words. 
* State of field should be covered by the statement of need section. I mention some related frameworks there, but I agree that it is very short and I will extend this section. The frameworks that you mention are, however, not really comparable to ARC-OPT, which considers reactive (instantaneous) whole-body motion control:
   - HPP is for motion planning
   - OCS2 and Crocoddyl deal with optimal control, mostly in the sense of trajectory optimization, although also online implementation are available
   - PINK/MINK are IK solvers, where ARC-OPT is also intended for dynamics computations
   - The humanoid control stack uses TSID, which is mentioned in my paper
   
Still I will have another look around what is out and relate the existing frameworks to my software.

**Comment by sea-bass** [comment]
Sounds good. As you said, I don't think that many extra words are needed, but some more content that better describes the specifics of your tool's capabilities and comparison to other related OSS software.

The initial paper, to me, mostly described the underlying theory but not the implementation.

**Comment by dmronga** [comment]
@sea-bass I update the paper draft according to your suggestions. In particular I ...
* Added more explanation on the design
* Added a code snipped showing a simple WBC setup
* Added some screenshots showing the result of the code snippet.
* Extended the state of the Art. I added reference to MINK and further WBC frameworks. The other tools you mentioned imo. serve other purposes. They are either for motion planning or optimal control
* Added a small section on ROS 2 support and Python bindings

Best regards

**Comment by sea-bass** [comment]
Looks great -- thank you!

Re: those other tools serving a different purpose. That's right, and my intention was to have some comparison of tools that solve QPs or nonlinear programs in general for various aspects of planning and control. But I see you've mentioned tools like Drake now as well, which is good.
