### ISSUE TITLE
Fix Floating Base Orientation

### ISSUE THREAD

**Issue by dmronga** [ARC-OPT/wbc#27]
The euler order in computing the orientation of the floating base seems to be incorrect.

**Comment by dmronga** [comment]
See [here](https://github.com/ARC-OPT/wbc/blob/f6af8ac5ea64d4d355fb0e68d27f2fb5dcac8187/src/core/RobotModel.cpp#L35)

**Comment by ibergonzani** [comment]
This should be solved, right?. Problem was given by the external state estimator
