### ISSUE TITLE
target_link_directories in src/solvers/eiquadprog/CMakeLists.txt breaks compatibility with older CMake versions

### ISSUE THREAD

**Issue by chhtz** [ARC-OPT/wbc#35]
This currently breaks our nightly builds on Ubuntu 18.04. According to https://cmake.org/cmake/help/latest/command/target_link_directories.html it "should be avoided where there are other choices."

@dmronga @pierrewillenbrockdfki

**Comment by pierrewillenbrockdfki** [comment]
18.04 only provides cmake 3.10, target_link_directories is available since cmake 3.13. so, that is not the way to go. making the eiquadprog known inside wbc as an IMPORTED_TARGET does work, once the pkg-config file of eiquadprog has been fixed.

**Comment by pierrewillenbrockdfki** [comment]
Either https://github.com/ARC-OPT/wbc/pull/36 or (better) https://github.com/ARC-OPT/wbc/pull/37 fix this, both require eiquadprog to be patched in a different way: https://github.com/ARC-OPT/package_set/pull/2
