### ISSUE TITLE
JOSS: State of the field

### ISSUE THREAD

**Issue by mhubii** [ARC-OPT/wbc#94]
Please always advise if incorrect.

Re: State of the field

Should other libraries such as etasl or optas be mentioned or is the WBC domain most relevant?

Refers https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
Good point. I added itasc (https://ieeexplore.ieee.org/document/4648032), which is I think the basis of etasl. Etasl itself is used for high-level task specification, so I would rather not mention it. Regarding optas, it seems that it is used for MPC and trajectory optimization. This library is only for WBC (instantaneous optimization).

**Comment by mhubii** [comment]
okay great, feel free to close any of the issue btw if you feel they got resolved @dmronga
