### ISSUE TITLE
JOSS: OSQP

### ISSUE THREAD

**Issue by mhubii** [ARC-OPT/wbc#95]
Please always advise if incorrect.

Is there a specific reason why `osqp` was not considered a solver? How difficult would the inclusion of `osqp` be?

I am referring to this benchmark: https://github.com/qpsolvers/qpbenchmark#plots

Refers https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
Yes, integrating osqp is definitely on my TODO list. I will integrate it

**Comment by dmronga** [comment]
Fixed by #101
