### ISSUE TITLE
JOSS: Docker

### ISSUE THREAD

**Issue by mhubii** [ARC-OPT/wbc#97]
Could you please provide me a Dockerfile to test the library?

Refers: https://github.com/openjournals/joss-reviews/issues/6696

**Comment by mhubii** [comment]
cheers, will have a look

**Comment by mhubii** [comment]
one more thing, could you just provide me the dockerfile as opposed to the container

**Comment by dmronga** [comment]
Sorry, I missed your query. Here is the docker file and install script: https://github.com/ARC-OPT/wbc/tree/master/docker. Both have to be in the same folder. Build/run with 
docker build -t image_name .
docker run -i -t image_name

**Comment by mhubii** [comment]
awesome, thank you for sharing. This should get me up to speed.

On a related note, would it be possible to merge the `RUN` commands for caching, e.g. in

https://github.com/ARC-OPT/wbc/blob/069dee2be489f2154e3d4892868b218fceaf4e9f/docker/Dockerfile#L3

```docker
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get -y install git cmake build-essential libboost-system-dev libboost-program-options-dev libboost-thread-dev libboost-test-dev pkg-config libeigen3-dev libboost-filesystem-dev
```

Please feel free to close this issue after
