### ISSUE TITLE
JOSS: Paper - Example

### ISSUE THREAD

**Issue by mhubii** [ARC-OPT/wbc#98]
Please always advise if incorrect.

The example section of the paper states an optimization problem. Is it correct, that the joint torques and external forces are part of the optimization? From my best understanding, this problem seeks to minimize ddq subject to constraints. It is stated that tau and f are minimized, too.

Refers https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
Yes it is correct. [This](https://github.com/ARC-OPT/wbc/blob/master/src/scenes/acceleration_reduced_tsid/AccelerationSceneReducedTSID.hpp) controller solves for joint accelerations and contact forces, while [this](https://github.com/ARC-OPT/wbc/blob/master/src/scenes/acceleration_tsid/AccelerationSceneTSID.hpp) controller solves for joint accelerations , torques and contact forces
